from typing import Dict

class Metadata:
    whisper_prompts: Dict[str, str] = {
        # Completely non-related prompt
        '0191da84-a057-7c94-bd0f-bbb441a25dd0': "A guide to planting and maintaining a home garden. Focus on key terms: soil, seeds, watering, sunlight, pruning, fertilizer, compost, growth, harvest, pest control, plant health, mulch, organic gardening, vegetables, fruits, herbs, and flowers.",

        # Sports commentary prompts with no sport specific terms
        '0191da84-a057-7c94-bd0f-bbb8bf91d733': "Transcribe live sports commentary. The commentary includes descriptions of play, actions of the teams, and decisions made by officials. Expect detailed analysis of strategies, player movements, and scoring opportunities. The transcription should reflect the live nature of the broadcast, with focus on critical moments and crowd reactions.",
        '0191da84-a057-7c94-bd0f-bbbb0f23b826': "Transcribe live sports commentary, with emphasis on real-time analysis of plays, including team formations, offensive and defensive strategies, scoring opportunities, and player substitutions.",

        # Sports commentary prompts with sport specific terms
        '0191da84-a057-7c94-bd0f-bbbc183784a5': "Transcribe live sports commentary. Focus on plays, actions, and decisions made during the game. Include key events like scoring, defensive plays, offensive moves, and critical moments of the game. The transcription should reflect the back-and-forth nature of the commentary.",
        '0191da84-a057-7c94-bd0f-bbb549b6d120': "Live sports commentary transcription. Focus on accurate recognition of terms like game, score, team, player, referee, goal, foul, penalty, substitution, coach, time-out, defense, offense, match, points, victory, championship, tournament, and competition.",

        # Sports commentary prompts with non-baseball sport specific terms (soccer, tennis)
        '0191da84-a057-7c94-bd0f-bbb6f5575c1b': "Soccer commentary transcription. Focus on key terms like goal, penalty kick, corner kick, free kick, offside, foul, yellow card, red card, goalkeeper, striker, midfielder, defender, substitution, extra time, shootout, tackle, dribble, pass, cross, header, throw-in, and match. Include team names and player names.",
        '0191da84-a057-7c94-bd0f-bbb77ccd1c41': "Tennis match commentary transcription. Focus on terms like serve, ace, double fault, break point, love, set, match point, forehand, backhand, volley, baseline, net, deuce, advantage, game, tiebreak, rally, drop shot, topspin, slice, and player names. Include tournament names and scoring system references.",

        # Baseball commentary prompts with sport specific terms (baseball)
        '0191da84-a057-7c94-bd0f-bbbddcbdbb58': "Transcribe baseball commentary. Focus on accurate transcription of technical terms: pitch count, ERA (earned run average), OBP (on-base percentage), slugging percentage, double switch, suicide squeeze, balk, intentional walk, pop fly, line drive, grounder, pick-off, designated hitter, utility player, foul tip, mound visit, changeup, curveball, slider, cutter, sinker, and fastball.",
        '0191da84-a057-7c94-bd0f-bbaa2acb0cec': "Baseball game commentary transcription. Focus on accurate recognition of key terms: pitch, strike, ball, foul ball, home run, RBI, double play, inning, outfield, infield, dugout, bullpen, mound, catcher, pitcher, batter, umpire, strikeout, fly ball, runs, bases loaded, grand slam, sacrifice fly, hit, bunt, steal, walk-off, pinch hitter, relief pitcher.",
        '0191da84-a057-7c94-bd0f-bbab1bdfff76': "Transcribe baseball commentary with focus on critical terms: pitch, strike, ball, foul ball, RBI, home run, double play, hit, infield, outfield, dugout, bullpen, catcher, pitcher, batter, umpire, strikeout, innings, fly ball, sacrifice fly, bunt, steal, error, force out, tag out, grand slam, pinch runner, walk-off, no-hitter, perfect game, relief pitcher, curveball, slider.",
        '0191da84-a057-7c94-bd0f-bbacd7f92353': "Accurately transcribe baseball commentary focusing on essential terms like strikeout, pitch, ball, home run, foul ball, RBI, innings, double play, dugout, bullpen, catcher, pitcher, batter, umpire, outfield, infield, sacrifice fly, bunt, steal, error, bases loaded, grand slam, pinch hitter, relief pitcher, walk-off, no-hitter, perfect game, curveball, slider, fastball.",
        '0191da84-a057-7c94-bd0f-bbad6623bbc2': "Focus on transcribing baseball game commentary with terms: pitch, strike, ball, foul ball, home run, RBI, double play, hit, inning, dugout, bullpen, catcher, pitcher, batter, umpire, strikeout, fly ball, walk-off, no-hitter, perfect game, grand slam, steal, bunt, bases loaded, sacrifice fly, force out, tag out, error, fastball, slider, curveball, relief pitcher.",
        '0191da84-a057-7c94-bd0f-bbae3977a4a7': "Transcribe live baseball commentary with emphasis on: pitch, strikeout, ball, foul ball, home run, RBI, inning, dugout, bullpen, catcher, pitcher, batter, umpire, double play, fly ball, sacrifice fly, steal, bunt, grand slam, bases loaded, walk-off, no-hitter, perfect game, relief pitcher, pinch hitter, force out, tag out, error, curveball, slider, fastball.",
        '0191da84-a057-7c94-bd0f-bbaf8b121e5b': "Accurately transcribe baseball commentary. Key terms: pitch, strikeout, ball, foul ball, home run, RBI, inning, double play, dugout, bullpen, catcher, pitcher, batter, umpire, outfield, infield, sacrifice fly, steal, bunt, grand slam, bases loaded, walk-off, no-hitter, perfect game, relief pitcher, pinch hitter, curveball, slider, fastball, force out, tag out, error.",
        '0191da84-a057-7c94-bd0f-bbb0af3cc427': "Transcribing baseball commentary with essential terminology: pitch, strike, ball, home run, RBI, inning, double play, fly ball, foul ball, dugout, bullpen, catcher, pitcher, batter, umpire, walk-off, no-hitter, perfect game, sacrifice fly, steal, bunt, grand slam, pinch hitter, relief pitcher, bases loaded, force out, tag out, error, curveball, slider, fastball, changeup.",
        '0191da84-a057-7c94-bd0f-bbb1d1ab70a8': "Baseball game transcription, focusing on terms like pitch, strikeout, ball, foul ball, home run, RBI, inning, double play, dugout, bullpen, catcher, pitcher, batter, umpire, outfield, infield, grand slam, sacrifice fly, walk-off, no-hitter, perfect game, pinch hitter, relief pitcher, steal, bunt, bases loaded, force out, tag out, error, curveball, slider, fastball.",
        '0191da84-a057-7c94-bd0f-bbb27705560a': "Transcribe baseball commentary with attention to essential terms: pitch, strikeout, ball, foul ball, home run, RBI, inning, double play, dugout, bullpen, catcher, pitcher, batter, umpire, fly ball, sacrifice fly, steal, bunt, grand slam, walk-off, no-hitter, perfect game, bases loaded, relief pitcher, pinch hitter, error, force out, tag out, curveball, slider, fastball.",
        '0191da84-a057-7c94-bd0f-bbb3a073bd95': "Baseball commentary transcription focusing on key game phrases: pitch, strike, ball, foul ball, home run, RBI, inning, double play, dugout, bullpen, catcher, pitcher, batter, umpire, strikeout, fly ball, sacrifice fly, steal, bunt, grand slam, bases loaded, walk-off, no-hitter, perfect game, relief pitcher, pinch hitter, force out, tag out, error, curveball, slider, fastball.",

        # No context. Only baseball specific terms.
        '0191da84-a057-7c94-bd0f-bbb9559a3a66': "Pitch, strike, ball, foul ball, home run, RBI, double play, inning, outfield, infield, dugout, bullpen, catcher, pitcher, batter, umpire, strikeout, fly ball, runs, bases loaded, grand slam, sacrifice fly, hit, bunt, steal, walk-off, pinch hitter, relief pitcher, curveball, slider.",
    }

    prompt_terms: Dict[str, Dict[str, float]] = {
        "pitcher": {"token_len": 5, "score": 0.82},
        "home run": {"token_len": 5, "score": 0.78},
        "catcher": {"token_len": 5, "score": 0.69},
        "inning": {"token_len": 4, "score": 0.69},
        "innings": {"token_len": 5, "score": 0.69},
        "fly ball": {"token_len": 5, "score": 0.67},
        "strikeout": {"token_len": 5, "score": 0.66},
        "bases loaded": {"token_len": 6, "score": 0.66},
        "batter": {"token_len": 5, "score": 0.65},
        "foul ball": {"token_len": 6, "score": 0.63},
        "RBI": {"token_len": 5, "score": 0.63},
        "fastball": {"token_len": 5, "score": 0.63},
        "shortstop": {"token_len": 5, "score": 0.59},
        "first baseman": {"token_len": 5, "score": 0.59},
        "second baseman": {"token_len": 5, "score": 0.59},
        "third baseman": {"token_len": 5, "score": 0.59},
        "left fielder": {"token_len": 5, "score": 0.56},
        "center fielder": {"token_len": 5, "score": 0.56},
        "right fielder": {"token_len": 5, "score": 0.56},
        "line drive": {"token_len": 5, "score": 0.56},
        "pitch count": {"token_len": 6, "score": 0.55},
        "double play": {"token_len": 5, "score": 0.49},
        "infield": {"token_len": 5, "score": 0.48},
        "outfield": {"token_len": 5, "score": 0.48},
        "dugout": {"token_len": 6, "score": 0.48},
        "at bat": {"token_len": 5, "score": 0.46},
        "grounder": {"token_len": 5, "score": 0.46},
        "pop fly": {"token_len": 5, "score": 0.45},
        "bullpen": {"token_len": 5, "score": 0.45},
        "umpire": {"token_len": 5, "score": 0.45},
        "changeup": {"token_len": 5, "score": 0.42},
        "pitch": {"token_len": 5, "score": 0.42},
        "relief pitcher": {"token_len": 6, "score": 0.40},
        "bunt": {"token_len": 5, "score": 0.39},
        "strike": {"token_len": 4, "score": 0.39},
        "curveball": {"token_len": 6, "score": 0.39},
        "designated hitter": {"token_len": 6, "score": 0.38},
        "sacrifice fly": {"token_len": 6, "score": 0.38},
        "on deck": {"token_len": 5, "score": 0.37},
        "slider": {"token_len": 5, "score": 0.37},
        "intentional walk": {"token_len": 6, "score": 0.36},
        "tag out": {"token_len": 5, "score": 0.35},
        "foul tip": {"token_len": 6, "score": 0.35},
        "walk-off": {"token_len": 6, "score": 0.35},
        "ERA": {"token_len": 4, "score": 0.35},
        "no-hitter": {"token_len": 7, "score": 0.34},
        "pinch hitter": {"token_len": 6, "score": 0.34},
        "OBP": {"token_len": 5, "score": 0.34},
        "slugging percentage": {"token_len": 7, "score": 0.34},
        "full count": {"token_len": 5, "score": 0.34},
        "force out": {"token_len": 5, "score": 0.32},
        "sinker": {"token_len": 5, "score": 0.32},
        "pick-off": {"token_len": 6, "score": 0.32},
        "grand slam": {"token_len": 5, "score": 0.31},
        "perfect game": {"token_len": 5, "score": 0.31},
        "pinch runner": {"token_len": 6, "score": 0.31},
        "fly out": {"token_len": 5, "score": 0.30},
        "earned run": {"token_len": 5, "score": 0.29},
        "knuckleball": {"token_len": 6, "score": 0.29},
        "fielder's choice": {"token_len": 7, "score": 0.29},
        "warning track": {"token_len": 5, "score": 0.29},
        "mound visit": {"token_len": 6, "score": 0.29},
        "balk": {"token_len": 5, "score": 0.29},
        "go-ahead run": {"token_len": 7, "score": 0.29},
        "3-2": {"token_len": 6, "score": 0.28},
        "0-1": {"token_len": 6, "score": 0.28},
        "0-2": {"token_len": 6, "score": 0.28},
        "1-0": {"token_len": 6, "score": 0.28},
        "1-1": {"token_len": 6, "score": 0.28},
        "1-2": {"token_len": 6, "score": 0.28},
        "2-1": {"token_len": 6, "score": 0.28},
        "2-2": {"token_len": 6, "score": 0.28},
        "2-0": {"token_len": 6, "score": 0.28},
        "3-1": {"token_len": 6, "score": 0.28},
        "3-0": {"token_len": 6, "score": 0.28},
        "on-base plus slugging (OPS)": {"token_len": 12, "score": 0.27},
        "passed ball": {"token_len": 6, "score": 0.27},
        "complete game": {"token_len": 5, "score": 0.27},
        "retire the side": {"token_len": 7, "score": 0.27},
        "scoreless inning": {"token_len": 6, "score": 0.27},
        "run-down": {"token_len": 6, "score": 0.27},
        "shutout": {"token_len": 5, "score": 0.27},
        "caught looking": {"token_len": 6, "score": 0.27},
        "long ball": {"token_len": 5, "score": 0.27},
        "inside pitch": {"token_len": 5, "score": 0.27},
        "stolen base percentage": {"token_len": 7, "score": 0.26},
        "box score": {"token_len": 5, "score": 0.26},
        "utility player": {"token_len": 6, "score": 0.26},
        "blown save": {"token_len": 5, "score": 0.25},
        "brushback pitch": {"token_len": 6, "score": 0.25},
        "off-speed pitch": {"token_len": 7, "score": 0.25},
        "drop third strike": {"token_len": 6, "score": 0.25},
        "tape-measure home run": {"token_len": 10, "score": 0.25},
        "drag bunt": {"token_len": 7, "score": 0.25},
        "defensive indifference": {"token_len": 6, "score": 0.25},
        "left on base (LOB)": {"token_len": 10, "score": 0.25},
        "punch and judy hitter": {"token_len": 9, "score": 0.25},
        "double switch": {"token_len": 5, "score": 0.25},
        "suicide squeeze": {"token_len": 6, "score": 0.25},
        "beanball": {"token_len": 5, "score": 0.25},
        "safety squeeze": {"token_len": 5, "score": 0.25},
        "little league homer": {"token_len": 6, "score": 0.25},
        "seeing-eye single": {"token_len": 7, "score": 0.25},
        "phantom tag": {"token_len": 6, "score": 0.25},
        "high heat": {"token_len": 5, "score": 0.25},
        "hidden ball trick": {"token_len": 6, "score": 0.25},
        "hot corner": {"token_len": 5, "score": 0.25},
        "golden sombrero": {"token_len": 8, "score": 0.25},
        "bullpen game": {"token_len": 6, "score": 0.25},
        "toe the rubber": {"token_len": 6, "score": 0.25},
        "chin music": {"token_len": 5, "score": 0.25},
        "mendoza line": {"token_len": 7, "score": 0.25},
        "sixth tool": {"token_len": 6, "score": 0.25},
        "quality start": {"token_len": 5, "score": 0.24},
        "dugout card": {"token_len": 7, "score": 0.24},
        "rounding the bases": {"token_len": 7, "score": 0.23},
        "dead ball": {"token_len": 5, "score": 0.23},
        "rubber game": {"token_len": 6, "score": 0.23},
        "save situation": {"token_len": 5, "score": 0.23},
        "payoff pitch": {"token_len": 6, "score": 0.23},
        "gapper": {"token_len": 5, "score": 0.23},
        "opposite field hit": {"token_len": 7, "score": 0.23},
        "set-up man": {"token_len": 7, "score": 0.23},
        "outfielder assist": {"token_len": 7, "score": 0.23},
        "shallow fly ball": {"token_len": 7, "score": 0.23},
        "push bunt": {"token_len": 6, "score": 0.23},
        "spray hitter": {"token_len": 6, "score": 0.23},
        "table setter": {"token_len": 6, "score": 0.23},
        "insurance run": {"token_len": 6, "score": 0.23},
        "three-quarters delivery": {"token_len": 7, "score": 0.23},
        "dirtball": {"token_len": 6, "score": 0.23},
        "spitball": {"token_len": 6, "score": 0.23},
        "take sign": {"token_len": 5, "score": 0.23},
        "DFA": {"token_len": 5, "score": 0.23},
        "missed sign": {"token_len": 6, "score": 0.22},
        "pulled the string": {"token_len": 7, "score": 0.22},
        "hard hit ball": {"token_len": 6, "score": 0.21},
        "mound": {"token_len": 5, "score": 0.21},
        "in the hole": {"token_len": 6, "score": 0.21},
        "clean-up": {"token_len": 6, "score": 0.20},
        "southpaw": {"token_len": 6, "score": 0.19},
        "soft hands": {"token_len": 5, "score": 0.18},
        "closer": {"token_len": 5, "score": 0.18},
        "cutter": {"token_len": 5, "score": 0.18},
        "no decision": {"token_len": 5, "score": 0.18},
        "chin guard": {"token_len": 5, "score": 0.18},
        "backstop": {"token_len": 5, "score": 0.16},
        "kick save": {"token_len": 5, "score": 0.16},
        "ball": {"token_len": 4, "score": 0.16},
        "moonshot": {"token_len": 6, "score": 0.16},
        "hit": {"token_len": 4, "score": 0.15},
        "heater": {"token_len": 5, "score": 0.14},
        "runs": {"token_len": 4, "score": 0.14},
        "ace": {"token_len": 4, "score": 0.14},
        "meatball": {"token_len": 5, "score": 0.11},
        "overthrow": {"token_len": 5, "score": 0.09},
        "error": {"token_len": 4, "score": 0.09},
        "sweet spot": {"token_len": 5, "score": 0.07},
        "steal": {"token_len": 5, "score": 0.07},
        "lost the handle": {"token_len": 6, "score": 0.06},
        "platoon": {"token_len": 5, "score": 0.05},
        "chopper": {"token_len": 5, "score": 0.04},
        "rally": {"token_len": 5, "score": 0.04},
        "green light": {"token_len": 5, "score": 0.04},
        "bomb": {"token_len": 4, "score": 0.04},
        "cycle": {"token_len": 4, "score": 0.03},
        "shift": {"token_len": 4, "score": 0.03},
        "bag": {"token_len": 4, "score": 0.03},
        "relay": {"token_len": 5, "score": 0.03},
        "stretch": {"token_len": 5, "score": 0.03},
        "knock": {"token_len": 5, "score": 0.02},
        "jam": {"token_len": 4, "score": 0.02},
        "rope": {"token_len": 5, "score": 0.02},
        "chop": {"token_len": 5, "score": 0.02},
        "shot": {"token_len": 4, "score": 0.02},
        "plugged": {"token_len": 5, "score": 0.02},
        "gap": {"token_len": 4, "score": 0.02},
        "laser": {"token_len": 5, "score": 0.02},
        "pepper": {"token_len": 5, "score": 0.02},
        "freeze": {"token_len": 5, "score": 0.02},
        "poaching": {"token_len": 5, "score": 0.02},
        "barrel": {"token_len": 5, "score": 0.02},
        "hole": {"token_len": 4, "score": 0.02},
        "hook": {"token_len": 4, "score": 0.01},
        "hold": {"token_len": 4, "score": 0.01},
        "lookout!": {"token_len": 6, "score": 0.01},
    }
